# Generated by Django 3.1.6 on 2021-02-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_details',
            new_name='Student_detail',
        ),
    ]
