# Generated by Django 3.1.6 on 2021-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210218_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='student_id',
            field=models.IntegerField(default=100),
        ),
    ]
